### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by paulincai** [Urigo/awesome-meteor#101]
raix:push - Push notifications for cordova (ios, android) browser (Chrome, Safari, Firefox).
phonegap-plugin-push used by raix:push has been archived.

**Comment by Urigo** [comment]
@paulincai could you submit a PR to update the content? I'll be happy to merge

**Comment by Urigo** [comment]
if there is no replacement, I would suggest to leave it there and add a `deprecated` notice next to it

**Comment by Urigo** [comment]
someone else created PRs that updated those
if not, please create another PR to update it
thank you for the feedback
