### ISSUE TITLE
Meteor Kitchen is missing

### ISSUE THREAD

**Issue by Billybobbonnet** [Urigo/awesome-meteor#21]
Hey, nice list you have here. I think [meteor kitchen](www.meteorkitchen.com) is missing. It is an awesome meteor code generator. It is still a work in progress but I think it is definitly worth a look. Nothing equivalent out there.

**Comment by gillesfabio** [comment]
@Billybobbonnet Thanks. I will add it.

**Comment by perak** [comment]
:+1: :)

**Comment by Urigo** [comment]
Added
