### ISSUE TITLE
Different layout

### ISSUE THREAD

**Issue by Urigo** [Urigo/awesome-meteor#22]
Hi @gillesfabio , great job!

I was looking for awsome-meteor a few days ago and haven't found yours for some reason so I've accidentally created another one:
https://github.com/Urigo/awesome-meteor

No worries, I will just pull request yours to add anything I have in there and delete my own.

But, I think that the layout and subjects I've created there are more similar to the other 'awesome' Github repos and might be easier to understand.

What do you think? should we change the layout?

Thanks

**Comment by gillesfabio** [comment]
Hi @Urigo,

Sorry for the delay.

I agree, your layout is easier to understand and feels more "awesome" GitHub repos. I even think of removing the gulp code and just keep a dead simple README. But I miss time to refactor everything, to properly maintain this repository. Would you want to become the new maintainer? I can transfer you the ownership (but you have to rename your repo first). Then, refactor it as better it could be :) (by removing all this ugly gulp stuff if you want to).

Let me know.

**Comment by Urigo** [comment]
@gillesfabio thanks!
I've changed the name of my repository and would love to do the work.
thank you for your work until now!  I will add your details inside the README as well to indicate that this is your project!

**Comment by gillesfabio** [comment]
@Urigo Thanks! :) Done. I'm sure you'll do a great job!

**Comment by Urigo** [comment]
Thanks friend.
Will start working hard to make sure your decision was the right one :)

**Comment by gillesfabio** [comment]
:+1:
