### ISSUE TITLE
Merge two repositories?

### ISSUE THREAD

**Issue by manrajgrover** [Urigo/awesome-meteor#50]
I had started something similar long back before stumbling on the awesome series and this repository. I wanted to share new things I stumble upon while exploring Meteor and group the resources for someone who later want to learn it. 

Here is the [link](https://github.com/ManrajGrover/mastering-meteor) to the repository.

I'm not sure whether to maintain it as a separate repository or merge it with yours. Also whether I can put it under "Awesome" category. I plan to maintain it regularly. Please share your thoughts.

**Comment by Urigo** [comment]
why not merge it with this one?

**Comment by manrajgrover** [comment]
Sorry for late reply.

Sure! I'll see if there aren't any duplicates and sent a PR accordingly.

**Comment by Rahman-S-M** [comment]
Having single repository helps developers quickly find resources and looking multiple locations

**Comment by Urigo** [comment]
closing as there was no response
