### ISSUE TITLE
No Payments section

### ISSUE THREAD

**Issue by tomasz-nolberczak** [Urigo/awesome-meteor#79]
There is no Payments section in the list, although there is such a link there.

**Comment by tomasz-nolberczak** [comment]
The project seems to be dead, so I am closing that issue.

**Comment by Urigo** [comment]
@tomasz-nolberczak just suggest a library for payments...

**Comment by tomasz-nolberczak** [comment]
Alright! :)

PayPal: https://atmospherejs.com/mrt/paypal
BrainTree: https://atmospherejs.com/patrickml/braintree
Stripe: https://atmospherejs.com/mrgalaxy/stripe

I think that also we could attach some links to NPM, but for now, it is enough.

PS: Let me also reopen this issue.

**Comment by ankitv89** [comment]
Add to the list - Instamojo - https://atmospherejs.com/instamojo/instamojo

**Comment by Urigo** [comment]
could you open a PR with those additions?
I want you to get the credit and become a contributor

**Comment by tomasz-nolberczak** [comment]
@Urigo done! You can find it here: https://github.com/Urigo/awesome-meteor/pull/89
