### ISSUE TITLE
Broken links (not the fix)

### ISSUE THREAD

**Issue by deadjdona** [Urigo/awesome-meteor#87]
## Following links are broken:
http://velocity.meteor.com/
http://madewith.meteor.com/
http://meteorcreate.com/
http://weekly.udgwebdev.com/

**Comment by tomasz-nolberczak** [comment]
@Urigo can we fix it?

**Comment by Urigo** [comment]
@tomasz-nolberczak yes and you can do to!
Can you submit a PR with the updated links or if you can't find just remove them?

**Comment by deadjdona** [comment]
velocity is gone
madewith is gone
meteorcreate not resolved
https://udgwebdev.com/ is working but it's in Spanish.
